version: '3.9'

services:
  pg:
    image: bitnami/postgresql
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid
    ports:
      - 5432:5432
  pg-test:
    image: bitnami/postgresql
    container_name: pg-test
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid-test
    ports:
      - 5433:5432
