name: Run Tests

on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: pg-test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate dev
      - run: npm run test
        env:
          NODE_ENV: "test"
          SEQUENTIAL_TESTS: true
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/pg-test?schema=public"

      